#!/usr/bin/env node

/**
 * Syncs ABIs from Foundry's compiled output to the app's contracts folder.
 * 
 * Usage: node scripts/sync-abis.js
 * 
 * This script reads the compiled contract ABIs from the `out/` folder
 * and generates TypeScript files with the ABIs for use in the frontend app.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Contracts to sync ABIs for
const contracts = [
  { name: 'Registry', path: 'src/Registry.sol' },
  { name: 'Chamber', path: 'src/Chamber.sol' },
  { name: 'MockERC20', path: 'test/mock/MockERC20.sol' },
  { name: 'MockERC721', path: 'test/mock/MockERC721.sol' },
];

function getAbi(contractName, contractPath) {
  const outPath = join(rootDir, 'out', `${contractName}.sol`, `${contractName}.json`);
  
  if (!existsSync(outPath)) {
    console.error(`❌ ABI not found: ${outPath}`);
    console.error(`   Run 'forge build' first to compile contracts.`);
    return null;
  }

  try {
    const artifact = JSON.parse(readFileSync(outPath, 'utf-8'));
    return artifact.abi;
  } catch (error) {
    console.error(`❌ Error reading ABI for ${contractName}:`, error.message);
    return null;
  }
}

function generateAbisFile(abis) {
  const lines = [
    '// Auto-generated by scripts/sync-abis.js - do not edit manually',
    '// Run `npm run sync-abis` or `make sync-abis` to regenerate',
    '',
  ];

  for (const [name, abi] of Object.entries(abis)) {
    const varName = name.charAt(0).toLowerCase() + name.slice(1) + 'Abi';
    lines.push(`export const ${varName} = ${JSON.stringify(abi, null, 2)} as const`);
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  console.log('🔄 Syncing ABIs from Foundry output...\n');

  const abis = {};
  let hasErrors = false;

  for (const contract of contracts) {
    const abi = getAbi(contract.name, contract.path);
    if (abi) {
      abis[contract.name] = abi;
      console.log(`✅ ${contract.name}: ${abi.length} ABI entries`);
    } else {
      hasErrors = true;
    }
  }

  if (hasErrors) {
    console.error('\n⚠️  Some ABIs could not be synced. Make sure to run `forge build` first.');
  }

  if (Object.keys(abis).length > 0) {
    const outputPath = join(rootDir, 'app', 'src', 'contracts', 'generated-abis.ts');
    const content = generateAbisFile(abis);
    writeFileSync(outputPath, content);
    console.log(`\n📝 Generated: app/src/contracts/generated-abis.ts`);
  }

  console.log('\n✨ ABI sync complete!');
}

main();
