name: Forge Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        working-directory: ${{ github.workspace }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        run: make ci-test
